global:
  evaluation_interval: 30s
  scrape_interval: 30s
  scrape_timeout: 10s
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
extraScrapeConfigs: |
   - job_name: 'snmp_teltonika'
     scrape_interval: 40s
     scrape_timeout: 21s
     static_configs:
       - targets:
         - 10.40.10.1
     metrics_path: /snmp
     params:
       auth: [snmpv2_com]
       module: [if_mib, teltonika]
     relabel_configs:
       - source_labels: [__address__]
         target_label: __param_target
       - source_labels: [__param_target]
         target_label: instance
       - target_label: __address__
         replacement: snmp-prometheus-snmp-exporter.monitoring.svc.cluster.local:9116
   - job_name: 'snmp_exporter'
     static_configs:
       - targets: ['snmp-prometheus-snmp-exporter.monitoring.svc.cluster.local:9116']

